baseURL = "https://martinw.eu"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Martins Smarthome Blog"
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "&copy; 2020 [Gethugothemes](https://gethugothemes.com) All Rights Reserved"
description = "This is martin"
google_analitycs_id = ""
google_tag_manager = ""
home = "Home"
logo = "images/Martin_hell_small_circle.png"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "Hallo, ich bin Martin. <br> Ich habe Spaß an Home Automation und schreibe darüber in diesem Blog"
[params.cta]
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
enable = true
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-youtube"
link = "https://www.youtube.com/channel/UCekTVmeJ6qkpjvqWt0rqpWg?view_as=subscriber"
[[params.social]]
icon = "ti-github"
link = "https://github.com/martinweu"

